print("Opening gate start")
print("Hi welcome friend")
print("how are you today?")
print("im good too")
print("lets get some fun friend")
print("today we will learn about python")
print("first we need open python")
print("we can open python on browser ")
print("than we use it to programing")
print("have fun >_<")